"""
consolidator.py

Reads every Markdown report generated by the PCI DSS Scanner and
creates a consolidated executive report.

Author: Essias Souza
"""

import os
import re

from glob import glob
from dataclasses import dataclass, field
from collections import defaultdict, Counter
from datetime import datetime


# ============================================================================
# Configuration
# ============================================================================

OUTPUT_DIRECTORY = "outputs"

REPORT_PATTERN = "*.md"

OUTPUT_REPORT = (
    "Consolidate_Report_"
    f"{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
)


# ============================================================================
# Data Models
# ============================================================================

@dataclass
class Finding:

    category: str

    severity: str

    rule: str

    evidence: str

    pci_reference: str


@dataclass
class WorkloadReport:

    file_name: str

    kind: str = ""

    name: str = ""

    namespace: str = ""

    replicas: str = ""

    findings: list = field(default_factory=list)


# ============================================================================
# Markdown Parser
# ============================================================================

class MarkdownReportParser:

    """
    Parses one report.md generated by report.py.
    """

    HEADER_KIND = re.compile(
        r"- Kind:\s*`(.*?)`"
    )

    HEADER_NAME = re.compile(
        r"- Name:\s*`(.*?)`"
    )

    HEADER_NAMESPACE = re.compile(
        r"- Namespace:\s*`(.*?)`"
    )

    HEADER_REPLICAS = re.compile(
        r"- Replicas:\s*`(.*?)`"
    )

    CATEGORY = re.compile(
        r"^## (.+)$"
    )

    TABLE_LINE = re.compile(
        r"^\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|$"
    )

    def parse(self, file_path):

        workload = WorkloadReport(
            file_name=os.path.basename(file_path)
        )

        current_category = None

        with open(
            file_path,
            encoding="utf-8"
        ) as report:

            for raw_line in report:

                line = raw_line.rstrip()

                #
                # Header
                #

                match = self.HEADER_KIND.search(line)

                if match:

                    workload.kind = match.group(1)

                    continue

                match = self.HEADER_NAME.search(line)

                if match:

                    workload.name = match.group(1)

                    continue

                match = self.HEADER_NAMESPACE.search(line)

                if match:

                    workload.namespace = match.group(1)

                    continue

                match = self.HEADER_REPLICAS.search(line)

                if match:

                    workload.replicas = match.group(1)

                    continue

                #
                # Category
                #

                match = self.CATEGORY.match(line)

                if match:

                    category = match.group(1)

                    if category != "Workload Identification":

                        current_category = category

                    continue

                #
                # Ignore empty lines
                #

                if not line:

                    continue

                #
                # Ignore markdown header
                #

                if line.startswith("| Severity"):

                    continue

                if line.startswith("| ---"):

                    continue

                #
                # Findings
                #

                if current_category:

                    match = self.TABLE_LINE.match(line)

                    if match:

                        workload.findings.append(

                            Finding(

                                category=current_category,

                                severity=match.group(1),

                                rule=match.group(2),

                                evidence=match.group(3),

                                pci_reference=match.group(4)

                            )

                        )

        return workload


# ============================================================================
# Report Loader
# ============================================================================

def load_reports():

    """
    Reads every markdown report inside outputs directory.
    """

    parser = MarkdownReportParser()

    reports = []

    files = sorted(

        glob(

            os.path.join(

                OUTPUT_DIRECTORY,

                REPORT_PATTERN

            )

        )

    )

    #
    # Ignore consolidated reports
    #

    files = [

        file

        for file in files

        if not os.path.basename(file).startswith(

            "Consolidate_Report_"

        )

    ]

    for file in files:

        reports.append(

            parser.parse(file)

        )

    return reports


# ============================================================================
# Statistics
# ============================================================================

def total_workloads(reports):

    return len(reports)


def total_findings(reports):

    return sum(

        len(report.findings)

        for report in reports

    )


def severity_counter(reports):

    counter = Counter()

    for report in reports:

        for finding in report.findings:

            counter[finding.severity] += 1

    return counter


def category_counter(reports):

    counter = Counter()

    for report in reports:

        for finding in report.findings:

            counter[finding.category] += 1

    return counter


def rule_counter(reports):

    counter = Counter()

    for report in reports:

        for finding in report.findings:

            counter[finding.rule] += 1

    return counter


def namespace_counter(reports):

    counter = Counter()

    for report in reports:

        counter[report.namespace] += len(

            report.findings

        )

    return counter


def workload_counter(reports):

    counter = Counter()

    for report in reports:

        counter[report.name] += len(

            report.findings

        )

    return counter


# ============================================================================
# Markdown Generation
# ============================================================================

def markdown_title():

    return (
        "# PCI DSS Consolidated Security Report\n\n"
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    )


def executive_summary(reports):

    severities = severity_counter(reports)

    content = []

    content.append(
        "## Executive Summary\n\n"
    )

    content.append(
        "| Metric | Value |\n"
    )

    content.append(
        "| --- | ---: |\n"
    )

    content.append(
        f"| Workloads Analyzed | {total_workloads(reports)} |\n"
    )

    content.append(
        f"| Total Findings | {total_findings(reports)} |\n"
    )

    content.append(
        f"| Critical | {severities.get('Critical', 0)} |\n"
    )

    content.append(
        f"| Warning | {severities.get('Warning', 0)} |\n"
    )

    content.append(
        f"| Info | {severities.get('Info', 0)} |\n\n"
    )

    return "".join(content)


def severity_summary(reports):

    severities = severity_counter(reports)

    content = []

    content.append(
        "## Findings by Severity\n\n"
    )

    content.append(
        "| Severity | Count |\n"
    )

    content.append(
        "| --- | ---: |\n"
    )

    for severity in ("Critical", "Warning", "Info"):

        content.append(
            f"| {severity} | {severities.get(severity, 0)} |\n"
        )

    content.append("\n")

    return "".join(content)


def category_summary(reports):

    categories = category_counter(reports)

    content = []

    content.append(
        "## Findings by Category\n\n"
    )

    content.append(
        "| Category | Count |\n"
    )

    content.append(
        "| --- | ---: |\n"
    )

    for category, total in sorted(
        categories.items()
    ):

        content.append(
            f"| {category} | {total} |\n"
        )

    content.append("\n")

    return "".join(content)


def rule_summary(reports):

    rules = rule_counter(reports)

    content = []

    content.append(
        "## Rule Frequency\n\n"
    )

    content.append(
        "| Rule | Occurrences |\n"
    )

    content.append(
        "| --- | ---: |\n"
    )

    for rule, total in sorted(
        rules.items(),
        key=lambda x: x[1],
        reverse=True
    ):

        content.append(
            f"| {rule} | {total} |\n"
        )

    content.append("\n")

    return "".join(content)


def namespace_summary(reports):

    namespaces = namespace_counter(reports)

    content = []

    content.append(
        "## Namespace Summary\n\n"
    )

    content.append(
        "| Namespace | Findings |\n"
    )

    content.append(
        "| --- | ---: |\n"
    )

    for namespace, total in sorted(
        namespaces.items(),
        key=lambda x: x[1],
        reverse=True
    ):

        content.append(
            f"| {namespace} | {total} |\n"
        )

    content.append("\n")

    return "".join(content)


def workload_summary(reports):

    workloads = workload_counter(reports)

    content = []

    content.append(
        "## Workload Summary\n\n"
    )

    content.append(
        "| Workload | Findings |\n"
    )

    content.append(
        "| --- | ---: |\n"
    )

    for workload, total in sorted(
        workloads.items(),
        key=lambda x: x[1],
        reverse=True
    ):

        content.append(
            f"| {workload} | {total} |\n"
        )

    content.append("\n")

    return "".join(content)


def findings_by_severity(
    reports,
    severity
):

    content = []

    content.append(
        f"## {severity} Findings\n\n"
    )

    content.append(
        "| Namespace | Workload | Rule | Evidence | PCI DSS |\n"
    )

    content.append(
        "| --- | --- | --- | --- | --- |\n"
    )

    found = False

    for report in reports:

        for finding in report.findings:

            if finding.severity != severity:

                continue

            found = True

            content.append(

                f"| {report.namespace} "

                f"| {report.name} "

                f"| {finding.rule} "

                f"| {finding.evidence} "

                f"| {finding.pci_reference} |\n"

            )

    if not found:

        content.append(
            "| None | None | None | None | None |\n"
        )

    content.append("\n")

    return "".join(content)


def detailed_findings(reports):

    content = []

    content.append(
        "# Detailed Findings\n\n"
    )

    for report in reports:

        content.append(
            f"## {report.namespace}/{report.name}\n\n"
        )

        content.append(
            f"- Kind: `{report.kind}`\n"
        )

        content.append(
            f"- Replicas: `{report.replicas}`\n"
        )

        content.append(
            f"- Findings: **{len(report.findings)}**\n\n"
        )

        if not report.findings:

            content.append(
                "No findings.\n\n"
            )

            continue

        content.append(
            "| Severity | Category | Rule | Evidence |\n"
        )

        content.append(
            "| --- | --- | --- | --- |\n"
        )

        for finding in report.findings:

            content.append(

                f"| {finding.severity} "

                f"| {finding.category} "

                f"| {finding.rule} "

                f"| {finding.evidence} |\n"

            )

        content.append("\n")

    return "".join(content)


def generate_markdown(reports):

    content = []

    content.append(
        markdown_title()
    )

    content.append(
        executive_summary(reports)
    )

    content.append(
        severity_summary(reports)
    )

    content.append(
        category_summary(reports)
    )

    content.append(
        rule_summary(reports)
    )

    content.append(
        namespace_summary(reports)
    )

    content.append(
        workload_summary(reports)
    )

    content.append(
        findings_by_severity(
            reports,
            "Critical"
        )
    )

    content.append(
        findings_by_severity(
            reports,
            "Warning"
        )
    )

    content.append(
        findings_by_severity(
            reports,
            "Info"
        )
    )

    content.append(
        detailed_findings(reports)
    )

    return "".join(content)


# ============================================================================
# Report Writer
# ============================================================================

def save_report(content):
    """
    Saves the consolidated Markdown report.
    """

    os.makedirs(
        OUTPUT_DIRECTORY,
        exist_ok=True
    )

    report_path = os.path.join(
        OUTPUT_DIRECTORY,
        OUTPUT_REPORT
    )

    with open(
        report_path,
        "w",
        encoding="utf-8"
    ) as report:

        report.write(content)

    return report_path


# ============================================================================
# Main
# ============================================================================

def main():

    print()
    print("=" * 70)
    print("PCI DSS Consolidated Report Generator")
    print("=" * 70)

    reports = load_reports()

    if not reports:

        print()
        print("No report.md files were found in outputs/.")
        return

    print()
    print(f"Reports loaded ............: {len(reports)}")

    findings = total_findings(reports)

    severities = severity_counter(reports)

    print(f"Total findings ...........: {findings}")
    print(
        f"Critical findings ........: "
        f"{severities.get('Critical', 0)}"
    )
    print(
        f"Warning findings .........: "
        f"{severities.get('Warning', 0)}"
    )
    print(
        f"Info findings ............: "
        f"{severities.get('Info', 0)}"
    )

    print()
    print("Generating consolidated report...")

    markdown = generate_markdown(
        reports
    )

    report_path = save_report(
        markdown
    )

    print()
    print("=" * 70)
    print("Consolidated report successfully generated.")
    print()
    print(f"Output file: {report_path}")
    print("=" * 70)
    print()


# ============================================================================
# Entry Point
# ============================================================================

if __name__ == "__main__":
    main()